apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "sharadupadhyaya7319@gmail.com"
  GMAIL_PASSWORD: "tbrq rgmv ypzl kmqy"  # generate your own app password here 
type: Opaque
